### ISSUE TITLE
out of bound exception

### ISSUE THREAD

**Issue by jjhesk** [KasualBusiness/MaterialNumberPicker#8]
i have got 

```

FATAL EXCEPTION: main
                                                        Process: h520.c, PID: 21035
                                                        java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
                                                            at hx520.hxhx.Rel.HXUtil$4.format(HXUtil.java:386)
                                                            at android.widget.NumberPicker.formatNumber(NumberPicker.java:1834)
                                                            at android.widget.NumberPicker.ensureCachedScrollSelectorValue(NumberPicker.java:1827)
                                                            at android.widget.NumberPicker.initializeSelectorWheelIndices(NumberPicker.java:1640)
                                                            at android.widget.NumberPicker.setFormatter(NumberPicker.java:1189)
                                                            at biz.kasual.materialnumberpicker.MaterialNumberPicker.<init>(MaterialNumberPicker.java:104)
                                                            at biz.kasual.materialnumberpicker.MaterialNumberPicker$Builder.build(MaterialNumberPicker.java:299)
                                                            at hx520.hxhx.Rel.HXUtil.genPicker(HXUtil.java:389)
                                                            at hx520.hxhx.main.pop_check.onViewCreated(pop_check.java:39)
                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1086)
                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                            at android.support.v4.app.Fragment.performResume(Fragment.java:2027)
                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1107)
                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:742)
                                                            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
                                                            at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                            at android.os.Looper.loop(Looper.java:135)
                                                            at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

```

when i posted a string array into the formatter.

**Comment by ghost** [comment]
How do you fix this?

**Comment by jjhesk** [comment]
why do u have this issue outstanding_

**Comment by ghost** [comment]
What do you mean?
